version: '3'

services:

  front:
    build: ./front_status
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back
      
  back:
    build: ./back_status
    container_name: back_status
    command: npm run start
    depends_on:
      - mysqldb
    ports: 
      - 3001:3001

  mysqldb:
    container_name: db_status
    env_file: ./.env
    environment:
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
    expose:
      - 3306
    image: mysql:8.0
    ports:
      - 3307:3306
    restart: always
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/

volumes: 
  db-config:
  db-data: